"""Creación de tablas

Revision ID: 5cf315c835d5
Revises: f6842814d075
Create Date: 2026-03-03 20:46:13.341936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5cf315c835d5'
down_revision = 'f6842814d075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellidos', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=50), nullable=True))
        batch_op.drop_column('apaterno')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apaterno', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('telefono')
        batch_op.drop_column('apellidos')

    # ### end Alembic commands ###
