"""Crear tabla Alumnos

Revision ID: 74eb086b5f8c
Revises: 
Create Date: 2026-02-24 20:33:44.508699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74eb086b5f8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reporte_diario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporte_diario',
    sa.Column('fecha', sa.DATE(), nullable=True),
    sa.Column('total_ventas', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cantidad_transacciones', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
