""" tabla Alumnos con cambios

Revision ID: eeb5e5b06a9e
Revises: 74eb086b5f8c
Create Date: 2026-02-24 20:37:33.093476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eeb5e5b06a9e'
down_revision = '74eb086b5f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellidos', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.drop_column('apaterno')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apaterno', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('telefono')
        batch_op.drop_column('apellidos')

    # ### end Alembic commands ###
