"""Creación de tablas

Revision ID: f6842814d075
Revises: 8f4654196a1d
Create Date: 2026-03-03 20:15:28.774891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6842814d075'
down_revision = '8f4654196a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('maestro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['maestro_id'], ['maestros.matricula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inscripcion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alumno_id', 'curso_id', name='uq_alumno_curso')
    )
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apaterno', sa.String(length=50), nullable=True))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('telefono')
        batch_op.drop_column('apellidos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellidos', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('telefono', mysql.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('apaterno')

    op.drop_table('inscripciones')
    op.drop_table('cursos')
    # ### end Alembic commands ###
